#!/usr/bin/env bash
# Regenerate docs/architecture/symbols.md from the actual source tree.
#
# This file is MECHANICAL — never hand-edit it. It gives agents a jump table
# (symbol -> file:line) so they can Read a narrow offset instead of whole files.
#
# Usage: ./scripts/gen-symbols.sh
set -euo pipefail

cd "$(dirname "$0")/.."
# Override to write elsewhere — check-doc-sync.sh uses this to diff without
# touching the tracked file.
OUT="${SYMBOLS_OUT:-docs/architecture/symbols.md}"

{
  echo "# Symbol Map (generated)"
  echo
  echo "Generated by \`scripts/gen-symbols.sh\`. Do not edit by hand."
  echo "Regenerate after any change to public classes/functions."
  echo
  echo "Use this to locate a symbol, then \`Read\` that file with a narrow"
  echo "\`offset\`/\`limit\` instead of opening the whole file."
  echo

  for f in $(git ls-files 'src/*.py' 'dashboard/*.py' 'scripts/*.py' | sort); do
    lines=$(wc -l < "$f" | tr -d ' ')
    echo "## \`$f\` ($lines lines)"
    echo '```'
    grep -nE '^(class |def |@app\.(get|post|put|delete|websocket))' "$f" \
      | sed -E 's/\(.*//; s/:$//' \
      | awk -F: '{printf "%-6s %s\n", $1, substr($0, index($0,$2))}' \
      || echo "(no top-level symbols)"
    echo '```'
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
